/*
 * @Author: JackLinYao
 * @Date: 2024-09-16 14:06:57
 * @LastEditTime: 2024-09-16 14:11:28
 * @LastEditors: JackLinYao
 * @Description: 
 * @FilePath: \jackLin-ui\pnpm-workspace.yaml
 * 
 */
packages:
  - 'packages/*'
